### ISSUE TITLE
关于老毛子固件锐捷V6.84认证

### ISSUE THREAD

**Issue by encil** [Talaxy009/MentoHUST-GZHU#1]
如题，360P2刷了个老毛子，发现无法破解锐捷认证，锐捷版本V6.84，请问是什么问题？需要我提供什么参数吗

**Comment by encil** [comment]
我也是gzhu，师兄，555

**Comment by Talaxy009** [comment]
如果你用的是固件自带的那个，那是无法在 GZHU 的校园网下使用的，原因是学校的认证需要特殊字段而与锐捷的版本无关。
老毛子的固件我接触的不多，建议你刷 PandoraBox 或 Openwrt 后使用本项目或者更优雅的[MiniEap](https://github.com/ysc3839/openwrt-minieap)，两个都是可以成功认证 GZHU 校园网的。
欢迎任何提问～

**Comment by encil** [comment]
你好，朋友的k2p路由器无法运行mentohust进程，权限也给了，运行了也会自动kill掉，请问是不是无法联网就自动关闭进程？

**Comment by encil** [comment]
固件也是pandorabox

**Comment by Talaxy009** [comment]
这算是我的锅了，没有说清楚这个二进制文件是给MT7620 用的，而 K2p 是 MT7621 的，去编译一个 MiniEAP 吧。
