### ISSUE TITLE
用putty等SSH软件登录后直接输入  mentohust 显示 permission denied

### ISSUE THREAD

**Issue by beyose** [Talaxy009/MentoHUST-GZHU#2]

**Comment by beyose** [comment]
![屏幕截图 2022-07-24 173017](https://user-images.githubusercontent.com/109812572/180642640-9740a077-583a-4692-ab4a-505a61b0fc6d.png)
我按照网上的方法尝试了一下，但是不管我输入其他什么指令它都会显示没找到>_<

**Comment by Talaxy009** [comment]
试试用 `chmod 777 ` 给 mentohust 加权限后再试试？

**Comment by Talaxy009** [comment]
在 WinSCP 里操作也可以，不过 “其他什么指令它都会显示没找到” ，这个有点奇怪，我也没思路
![image](https://user-images.githubusercontent.com/41264828/180674635-c7b1ec33-3cc3-4bfd-a8f7-5b9b69f053f0.png)

**Comment by beyose** [comment]
> 试试用 `chmod 777 ` 给 mentohust 加权限后再试试？
使用这个指令也会显示没有权限，不过通过后面那个方法可以。
![屏幕截图 2022-07-28 235412](https://user-images.githubusercontent.com/109812572/181583694-81229785-2280-407d-a6d2-51565b589111.png)

**Comment by beyose** [comment]
> 
通过在WinSCP中直接更改文件属性已经成功打开并连接，感谢师兄\(^o^)/~
![屏幕截图 2022-07-28 234424](https://user-images.githubusercontent.com/109812572/181584755-421aa141-8ba3-479e-96f7-5a047edd3996.png)

**Comment by beyose** [comment]
> 

通过在WinSCP中直接更改文件属性已经成功打开并连接，感谢师兄\(^o^)/~
![屏幕截图 2022-07-28 234424](https://user-images.githubusercontent.com/109812572/181584755-421aa141-8ba3-479e-96f7-5a047edd3996.png)

**Comment by Talaxy009** [comment]
不客气👌
